INSERT INTO USERS (ID, USERNAME,PASSWORD) VALUES (1, 'admin','password');
INSERT INTO USERS (ID, USERNAME,PASSWORD) VALUES (2, 'user','password');
INSERT INTO USERS (ID, USERNAME,PASSWORD) VALUES (3, 'write','password');

INSERT INTO ROLES (ID, ROLENAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO ROLES (ID, ROLENAME) VALUES (2, 'ROLE_USER');

INSERT INTO USER_ROLE_MAPPING (ID, USERID, ROLEID) VALUES (1, 1, 1);
INSERT INTO USER_ROLE_MAPPING (ID, USERID, ROLEID) VALUES (2, 2, 2);
INSERT INTO USER_ROLE_MAPPING (ID, USERID, ROLEID) VALUES (3, 3, 1);
INSERT INTO USER_ROLE_MAPPING (ID, USERID, ROLEID) VALUES (4, 3, 2);